---
- name: Setup GitHub Runner
  hosts: git-runner
  become: yes
  tasks:
    - name: Create actions-runner directory
      file:
        path: /home/ubuntu/actions-runner
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Download GitHub Actions runner using curl
      command: curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
      args:
        chdir: /home/ubuntu/actions-runner/

    - name: Verify download checksum
      become_user: ubuntu
      shell: echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c
      args:
        chdir: /home/ubuntu/actions-runner

    - name: Extract GitHub Runner
      become_user: ubuntu
      unarchive:
        src: /home/ubuntu/actions-runner/actions-runner-linux-x64-2.317.0.tar.gz
        dest: /home/ubuntu/actions-runner
        remote_src: yes
    
    - name: Check if GitHub Runner is already configured
      stat:
        path: /home/ubuntu/actions-runner/.runner
      register: runner_config

    - name: Configure GitHub Runner
      become_user: ubuntu
      shell: ./config.sh --url https://github.com/Konami33/Git-runner-using-ansible --token AQGGSGXHDSSZOFPPHRW3TITGR3CDQ --name "Git-runner" --unattended
      args:
        chdir: /home/ubuntu/actions-runner
      when: not runner_config.stat.exists

    - name: Check if GitHub Runner service is already installed
      stat:
        path: /etc/systemd/system/actions.runner.Konami33-Git-runner-using-ansible.Git-runner.service
      register: runner_service_installed

    - name: Install GitHub Runner service
      shell: sudo ./svc.sh install
      args:
        chdir: /home/ubuntu/actions-runner  
      when: not runner_service_installed.stat.exists

    - name: Check if GitHub Runner service is running
      systemd:
        name: actions.runner.Konami33-Git-runner-using-ansible.Git-runner.service
        state: started
      register: runner_service

    - name: Start GitHub Runner service if not running
      shell: |
        sudo ./svc.sh start
      args:
        chdir: /home/ubuntu/actions-runner
      when: runner_service is failed
